name: PsychEngine Android Build
on:
  push:
    branches:
      - main

jobs:
  buildAndroid:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Haxe
      run: |
        sudo apt-get update
        sudo apt-get install haxe -y

    - name: Install Haxelib
      run: haxelib setup ~/haxelib

    - name: Install Dependencies
      run: |
        haxelib install hmm --quiet
        haxelib run hmm install --quiet
          
    - name: Build Android Project
      run: haxelib run lime build android

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: export/release/android/bin
